Add pp_ser to build_command

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4843,26 +4843,6 @@ fi
 fi
 
 
-if test "x$enable_serialization" = "xyes"; then :
-  if test -n "${SERIALBOX2ROOT}" ; then
-    if test -f "${SERIALBOX2ROOT}/python/pp_ser/pp_ser.py" ; then
-      if test -x "${SERIALBOX2ROOT}/python/pp_ser/pp_ser.py" ; then
-         SERIALBOX2_PPSER="${SERIALBOX2ROOT}/python/pp_ser/pp_ser.py"
-       else
-         echo "pp_ser.py script from Serialbox2 is not executable"
-         exit 1
-      fi
-    else
-      echo "Cannot find pp_ser.py script from Serialbox2"
-      exit 1
-    fi
-  else
-    echo "Error: Serialization is enabled but SERIALBOX2ROOT is not defined"
-    exit 1
-  fi
-fi
-
-
 PROFILE_LIB=""
 PROFILE_INCLUDE=""
 
@@ -6487,6 +6467,27 @@ if [ "x$target_os" = xsuperux ] ; then
     arch=$(echo ${target_cpu:0:2} | tr ":lower:" ":upper:")
 else
     arch=$target_cpu
+fi
+
+
+if test "x$enable_serialization" = "xyes"; then :
+  if test -n "${SERIALBOX2ROOT}" ; then
+    if test -f "${SERIALBOX2ROOT}/python/pp_ser/pp_ser.py" ; then
+      if test -x "${SERIALBOX2ROOT}/python/pp_ser/pp_ser.py" ; then
+         SERIALBOX2_PPSER="${SERIALBOX2ROOT}/python/pp_ser/pp_ser.py"
+         make_command="${SERIALBOX2_PPSER} -r -d ${my_iconppdir} src;$make_command;"
+       else
+         echo "pp_ser.py script from Serialbox2 is not executable"
+         exit 1
+      fi
+    else
+      echo "Cannot find pp_ser.py script from Serialbox2"
+      exit 1
+    fi
+  else
+    echo "Error: Serialization is enabled but SERIALBOX2ROOT is not defined"
+    exit 1
+  fi
 fi
 
 
