Revert "Merge updates from release candidate 2.6.2 into icon-nwp-dev (prepared by Daniel Reinert)"
original commit has been squashed unintentionally ==> revert

This reverts commit 31fa66d77ccae7321a67ed51a0c5eb49a84dd4ad.

diff --git a/run/make_target_runscript b/run/make_target_runscript
--- a/run/make_target_runscript
+++ b/run/make_target_runscript
@@ -1,137 +1,158 @@
-#! /bin/bash
-#______________________________________________________________________________
+#!/bin/ksh
+#==============================================================================
 #
-# This script makes finally the run scripts
+# This script makes the run scripts for the icon_testbed
 #
-# Original version by Leonidas Linardakis, MPI-M, 2010-11-22
-#______________________________________________________________________________
-
-set -eu
-
-typeset -a free_variable
-typeset -a free_variable_value
-typeset -i no_of_free_variables
-no_of_free_variables=0
-
-use_mpi=""
-use_openmp=""
-use_cpu_time=""
-use_mpi_procs_pernode=""
-use_nproma=""
-use_openmp_threads=""
-use_omp_stacksize=""
-use_resources=""
-use_memory_model=""
-use_memory=""
-use_node_usage=""
-use_nodes=""
-use_account_no=""
-use_queue=""
-output_name=""
-input_name=""
-job_name=""
-input_folder=""
-output_folder=""
-use_shell=""
+# Leonidas Linardakis, MPI-M, 2010-11-22
+#
+#==============================================================================
+scriptname=$0
+# echo "$scriptname: Start"
 
 IFS=" ="
-
 eval_argument ()
 {
-    case $1 in
-        "with_mpi")          use_mpi=$2 ;;
-        "with_openmp")       use_openmp=$2 ;;
-        "cpu_time")          use_cpu_time=$2 ;;
-        "mpi_procs_pernode") use_mpi_procs_pernode=$2 ;;
-        "nproma")            use_nproma=$2 ;;
-        "openmp_threads")    use_openmp_threads=$2 ;;
-        "omp_stacksize")     use_omp_stacksize=$2 ;;
-        "resources")         use_resources=$2 ;;
-        "memory_model")      use_memory_model=$2 ;;
-        "memory")            use_memory=$2 ;;
-        "node_usage")        use_node_usage=$2 ;;
-        "no_of_nodes")       use_nodes=$2 ;;
-        "account_no")        use_account_no=$2 ;;
-        "queue")             use_queue=$2 ;;
-        "out_script")        output_name=$2 ;;
-        "in_script")         input_name="$input_name $2" ;;
-        "job_name")          job_name="$2" ;;
-        "in_folder")         input_folder=$2 ;;
-        "out_folder")        output_folder=$2 ;;
-        "with_shell")        use_shell=$2 ;;
-        *)
-            ((no_of_free_variables+=1))
-            free_variable[$no_of_free_variables]=$1
-            free_variable_value[$no_of_free_variables]=$2
-    esac
-    input_name="${input_name#"${input_name%%[![:space:]]*}"}"
+  case $1 in
+  "with_mpi" ) use_mpi=$2
+  ;;
+  "with_openmp" ) use_openmp=$2
+  ;;
+  "cpu_time" ) use_cpu_time=$2
+#     echo "use_cpu_time=$use_cpu_time"
+  ;;
+  "mpi_procs_pernode" ) use_mpi_procs_pernode=$2
+#     echo "use_mpi_procs_pernode=$use_mpi_procs_pernode"
+  ;;
+  "nproma" ) use_nproma=$2
+  ;;
+  "openmp_threads" ) use_openmp_threads=$2
+#     echo "use_openmp_threads=$use_openmp_threads"
+  ;;
+  "omp_stacksize" ) use_omp_stacksize=$2
+  ;;
+  "resources" ) use_resources=$2
+  ;;
+  "memory_model" ) use_memory_model=$2
+  ;;
+  "memory" ) use_memory=$2
+  ;;
+  "node_usage" ) use_node_usage=$2
+  ;;
+  "no_of_nodes" ) use_nodes=$2
+  ;;
+  "account_no" ) use_account_no=$2
+  ;;
+  "queue" ) use_queue=$2
+  ;;
+  "out_script" ) output_name=$2
+#     echo "output_name=$output_name"
+  ;;
+  "in_script" ) input_name="$input_name $2"
+  ;;
+  "job_name" ) job_name="$2"
+  ;;
+  "in_folder" ) input_folder=$2
+  ;;
+  "out_folder" ) output_folder=$2
+  ;;
+  "with_shell" ) use_shell=$2
+  ;;
+  *) let "no_of_free_variables=$no_of_free_variables+1"
+     free_variable[$no_of_free_variables]=$1
+     free_variable_value[$no_of_free_variables]=$2
+#      echo "free_variable=${free_variable[$no_of_free_variables]} with value=${free_variable_value[$no_of_free_variables]}"
+#      exit -1 ;;
+  esac
 }
 
-#______________________________________________________________________________
-# main program
+get_first_name()
+{
+  first_name=$1
+}
+
+
 
 call_folder=$(pwd)
 cd $(dirname $0)
 this_folder=$(pwd)
 base_folder=${this_folder%/*}
 
-# initialize "use_..." variables, which characterize the target
-# system, with values stored up by the "configure" script in
-# set-up.info
-
-source $base_folder/run/set-up.info
-
-# now use arguments passed to make_target_runscript to adjust
-# "use_..." variables echo "Arguments for make_target_runscript:"
-
-for arg
-do
-    eval_argument $arg
+for config_file in ${base_folder}/run/set-up.info ${base_folder}/run/create_target_header; do
+  if test -f ${config_file} ; then
+    source ${config_file}
+  else
+    echo "Could NOT find config file '${config_file}' - exit"
+    exit 1
+  fi
 done
 
+let "no_of_free_variables=0"
+for arg
+do
+  eval_argument $arg
+done
+
+
 if [[ "x$input_name" == "x" ]] ; then
-  echo "[ERROR] Specify in_script=<name>."
+  echo "Specify in_script=<name>.  Exit"
   exit -1
 fi
 
-first_name=${input_name%% *}
-output_name=${output_name:="$first_name.run"}
-run_folder=${input_folder:=run}
-output_local_folder=${output_folder:=$input_folder}
-output_folder="$base_folder/$output_local_folder"
-output_script="$output_folder/$output_name"
+echo $input_name
+get_first_name $input_name
+
+
+if [[ "x$output_name" == "x" ]] ; then
+  output_name=$first_name.run
+fi
+
+if [[ "x$input_folder" == "x" ]] ; then
+  input_folder=run
+fi
+
+if [[ "x$input_folder" == "x" ]] ; then
+  run_folder=run
+else
+  run_folder=$input_folder
+fi
+
+if [[ "x$output_folder" == "x" ]] ; then
+  output_local_folder=$input_folder
+fi
+
+output_folder=$base_folder/$output_local_folder
+output_script=$output_folder/$output_name
 
 if [[ ! -d $output_folder ]] ; then
   mkdir $output_folder
 fi
 
+
 job_name=${job_name:=$output_name}
-
-echo -n "Creating the run script  $output_script ... "
-
-# source the script create_target_header to define the shell function create_target_header
-source $base_folder/run/create_target_header
-
-# execute the shell function create_target_header to create the header
+# echo job_name=$job_name
 create_target_header
 
-# add the script for the experiment and the execution:
 input_script=$base_folder/$input_folder/$input_name
 for in_name in $input_name
 do
   cat_file=$base_folder/$input_folder/$in_name
   if [[ ! -f $cat_file ]] ; then
-    echo "[ERROR] script $cat_file not found"
+    echo "script $cat_file not found"
     exit 1
   fi
   cat $cat_file >> $output_script
 done
 
 chmod +x $output_script
+if [[ "x$use_submit" == "x" ]] ; then
+  echo "$output_script is created."
+else
+  echo "$output_script is created. Submit is $use_submit."
+fi
+# echo "---------------------------"
 
-echo "done."
 
 cd $call_folder
+exit
+#------------------------------------------------------------------------------
 
-exit 0
-#______________________________________________________________________________
